---
- name: Install MariaDB packages
  apt: pkg={{item}} state=present
  with_items:
    - mariadb-server
    - mariadb-client
    - mariadb-common

- name: Listen on all interfaces
  lineinfile: dest=/etc/mysql/my.cnf regexp="^bind-address" line="bind-address            = 0.0.0.0"
  notify: Restart MariaDB

- name: Find out databases already created
  command: >
    /usr/bin/mysql
    -e "SHOW DATABASES;"
  register: databases
  tags:
    - provision
    - create-db

- debug: var=databases.stdout.find('pasteque')
  tags:
    - provision
    - create-db

- name: Copy database init script
  template: src="{{ item }}" dest=/tmp
  with_items:
    - init-mysql.sql
  when: databases.stdout.find('pasteque') == -1
  tags:
    - create-db

- name: Copy database init script
  template: src="{{ item }}" dest=/tmp
  with_items:
    - init-categories.sql
    - init-users.sql
    - init-products.sql
    - init-logo.sql
  when: databases.stdout.find('pasteque') >= 1
  tags:
    - provision

- name: Execute database init script
  shell: "mysql < /tmp/{{ item }}"
  with_items:
    - init-mysql.sql
  when: databases.stdout.find('pasteque') == -1
  tags:
    - create-db

- name: Execute database init script
  shell: "mysql pasteque < /tmp/{{ item }}"
  with_items:
    - init-categories.sql
    - init-users.sql
    - init-products.sql
    - init-logo.sql
  when: databases.stdout.find('pasteque') >= 1
  tags:
    - provision
