---
- name: Install MariaDB packages
  apt: pkg={{item}} state=present
  with_items:
    - mariadb-server
    - mariadb-client
    - mariadb-common

- name: Listen on all interfaces
  lineinfile: dest=/etc/mysql/my.cnf regexp="^bind-address" line="bind-address            = 0.0.0.0"
  notify: Restart MariaDB

- name: Copy database init script
  template: src=init-mysql.sql dest=/tmp

- name: Execute database init script
  shell: mysql < /tmp/init-mysql.sql
