---
- name: Update apt-cache
  apt: update_cache=yes
  
- name: Upgrade all packages
  apt: upgrade=dist
    
- name: Install ntp
  apt: name=ntp state=present
  tags: ntp

- name: Configure ntp file
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  tags: ntp
  notify: restart ntp

- name: Start the ntp service
  service: name=ntp state=started enabled=yes
  tags: ntp

- name: Fill hosts file
  local_action: lineinfile dest=/etc/hosts regexp="{{ ansible_hostname }}" line="{{ ansible_eth0.ipv4.address }} {{ ansible_hostname }}"

- name: debug
  debug: var=ansible_hostname
  
