---
- name: Install Nginx
  apt: pkg={{item}} state=present
  with_items:
    - nginx
    - php5
    - php5-mysql
    - php5-memcache
    - php5-intl
    - php5-gd
    - php5-fpm
    - mariadb-server
    - mariadb-client
    - mariadb-common

- name: Create docroot
  file: path={{ www_dir }} state=directory

- name: Download Pasteque Server
  get_url: url={{ pasteque_src_url }} dest=/tmp

- name: Unarchive Pasteque Server
  shell: tar -xzf /tmp/{{ pasteque_archive }} --directory {{ www_dir }} # Not using unarchive module because of an ansible bug with become

- name: Remove old directory
  shell: rm -rf {{ pasteque_dir }}

- name: Rename directory
  shell: mv {{ www_dir }}/pasteque-server-6.0.4 {{ pasteque_dir }}

- name: Create VirtualHost (pasteque)
  template: src=vhost.j2 dest={{ nginx_conf_path }}/sites-available/{{ pasteque_host }}.conf
  notify: Restart Nginx

- name: Disable ipv6 listening
  lineinfile: dest=/etc/nginx/sites-available/default regexp="^.+ipv6only=on" state=absent

- name: Add vhost symlink in sites-enabled.
  file:
    src: "{{ nginx_conf_path }}/sites-available/{{ pasteque_host }}.conf"
    dest: "{{ nginx_conf_path }}/sites-enabled/{{ pasteque_host }}.conf"
    state: link
  notify: Restart Nginx

- name: Display URL
  debug: msg=Pasteque URL is http://{{ pasteque_host }} with {{ pasteque_host }} {{ ansible_eth0["ipv4"]["address"] }}

- name: Create phpinfo
  template: src=phpinfo.php.j2 dest={{ pasteque_dir }}/phpinfo.php

- name: Copy config file
  shell: cp {{ pasteque_dir }}/config-sample.php {{ pasteque_dir }}/config.php

- name: Copy modules config file
  template: src=core-modules/modules/static/config.php.j2 dest={{ pasteque_dir }}/core_modules/modules/static/config.php

- name: debug
  debug: var=hostvars['pasteque-db']['ansible_eth0']['ipv4']['address']
  tags: [debug]

- name: Copy database config file
  template: src=core-modules/database/static/config.php.j2 dest={{ pasteque_dir }}/core_modules/database/static/config.php

- name: Fill hosts file
  local_action: lineinfile dest=/etc/hosts regexp="{{ pasteque_host }}" line="{{ ansible_eth0.ipv4.address }} {{ pasteque_host }}"
