---
- hosts: all
  become: true
  roles:
    - common

- hosts: web
  become: true
  roles:
    - pasteque

- hosts: database
  become: true
  roles:
    - mariadb

- hosts: web
  become: true
  tasks:
    - name: Configure local haproxy
      local_action: template src=haproxy.cfg.j2 dest=/etc/haproxy/haproxy.cfg
